# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: splade.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'splade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csplade.proto\x12\x06splade\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x82\x01\n\x11\x45mbeddingResponse\x12;\n\tembedding\x18\x01 \x03(\x0b\x32(.splade.EmbeddingResponse.EmbeddingEntry\x1a\x30\n\x0e\x45mbeddingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x8c\x01\n\x16TokenEmbeddingResponse\x12@\n\tembedding\x18\x01 \x03(\x0b\x32-.splade.TokenEmbeddingResponse.EmbeddingEntry\x1a\x30\n\x0e\x45mbeddingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x9b\x01\n\x10\x45mbeddingService\x12>\n\x0cGetEmbedding\x12\x13.splade.TextRequest\x1a\x19.splade.EmbeddingResponse\x12G\n\x10GetEmbeddingStrs\x12\x13.splade.TextRequest\x1a\x1e.splade.TokenEmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGENTRY']._loaded_options = None
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_options = b'8\001'
  _globals['_TOKENEMBEDDINGRESPONSE_EMBEDDINGENTRY']._loaded_options = None
  _globals['_TOKENEMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_options = b'8\001'
  _globals['_TEXTREQUEST']._serialized_start=24
  _globals['_TEXTREQUEST']._serialized_end=51
  _globals['_EMBEDDINGRESPONSE']._serialized_start=54
  _globals['_EMBEDDINGRESPONSE']._serialized_end=184
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_start=136
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_end=184
  _globals['_TOKENEMBEDDINGRESPONSE']._serialized_start=187
  _globals['_TOKENEMBEDDINGRESPONSE']._serialized_end=327
  _globals['_TOKENEMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_start=279
  _globals['_TOKENEMBEDDINGRESPONSE_EMBEDDINGENTRY']._serialized_end=327
  _globals['_EMBEDDINGSERVICE']._serialized_start=330
  _globals['_EMBEDDINGSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
